import type {Pool} from 'pg';

type Input={workflowCode:string;input:string;requesterIdentityId?:string;sourceType?:string;sourceId?:string};
type Result={provider:string;model:string;text:string;inputTokens:number;outputTokens:number;cost:string};
const jsonHeaders={'content-type':'application/json','accept':'application/json'};
const env=(k:string)=>process.env[k];
const safeJson=(text:string)=>{try{return JSON.parse(text)}catch{return {text}}};

async function openai(model:string,input:string):Promise<Result>{const key=env('OPENAI_API_KEY');if(!key)throw new Error('OPENAI_API_KEY_NOT_CONFIGURED');const r=await fetch(`${env('OPENAI_BASE_URL')??'https://api.openai.com/v1'}/responses`,{method:'POST',headers:{...jsonHeaders,authorization:`Bearer ${key}`},body:JSON.stringify({model,input})});if(!r.ok)throw new Error(`OPENAI_HTTP_${r.status}`);const d:any=await r.json();return{provider:'openai',model,text:d.output_text??'',inputTokens:d.usage?.input_tokens??0,outputTokens:d.usage?.output_tokens??0,cost:'0'};}
async function gemini(model:string,input:string):Promise<Result>{const key=env('GEMINI_API_KEY');if(!key)throw new Error('GEMINI_API_KEY_NOT_CONFIGURED');const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(key)}`,{method:'POST',headers:jsonHeaders,body:JSON.stringify({contents:[{parts:[{text:input}]}]})});if(!r.ok)throw new Error(`GEMINI_HTTP_${r.status}`);const d:any=await r.json();return{provider:'gemini',model,text:d.candidates?.[0]?.content?.parts?.map((p:any)=>p.text??'').join('')??'',inputTokens:d.usageMetadata?.promptTokenCount??0,outputTokens:d.usageMetadata?.candidatesTokenCount??0,cost:'0'};}

export class AiGateway{constructor(private readonly pool:Pool){}
 async execute(input:Input):Promise<Result>{const wf=await this.pool.query<any>('SELECT id,provider_policy FROM ai_workflows WHERE code=$1 AND enabled=true',[input.workflowCode]);if(!wf.rows[0])throw new Error('AI_WORKFLOW_NOT_FOUND');const pv=await this.pool.query<any>('SELECT id,system_prompt,user_template FROM ai_prompt_versions WHERE workflow_id=$1 AND enabled=true ORDER BY version DESC LIMIT 1',[wf.rows[0].id]);if(!pv.rows[0])throw new Error('AI_PROMPT_NOT_FOUND');const providers=Array.isArray(wf.rows[0].provider_policy?.providers)?wf.rows[0].provider_policy.providers:['openai','gemini'];const body=`${pv.rows[0].system_prompt}\n\n${pv.rows[0].user_template.replace('{{input}}',input.input)}`;const run=await this.pool.query<any>('INSERT INTO ai_execution_runs(workflow_id,prompt_version_id,requester_identity_id,source_type,source_id,status,created_at,started_at,input_metadata) VALUES($1,$2,$3,$4,$5,\'running\',NOW(),NOW(),$6) RETURNING id',[wf.rows[0].id,pv.rows[0].id,input.requesterIdentityId??null,input.sourceType??null,input.sourceId??null,JSON.stringify({workflow:input.workflowCode})]);let last='AI_EXECUTION_FAILED';for(const provider of providers){try{const cfg=await this.pool.query<any>('SELECT id,model_policy FROM ai_providers WHERE name=$1 AND enabled=true',[provider]);if(!cfg.rows[0])continue;const model=cfg.rows[0].model_policy?.default_model??(provider==='gemini'?'gemini-2.5-flash':'gpt-5.6-luna');const result=provider==='gemini'?await gemini(model,body):provider==='openai'?await openai(model,body):(()=>{throw new Error('AI_PROVIDER_NOT_IMPLEMENTED')})();await this.pool.query('UPDATE ai_execution_runs SET provider_id=$1,model=$2,status=\'succeeded\',input_tokens=$3,output_tokens=$4,cost=$5,output_metadata=$6,completed_at=NOW() WHERE id=$7',[cfg.rows[0].id,result.model,result.inputTokens,result.outputTokens,result.cost,JSON.stringify({textLength:result.text.length}),run.rows[0].id]);return result;}catch(e){last=e instanceof Error?e.message:'AI_EXECUTION_FAILED';}}
 await this.pool.query('UPDATE ai_execution_runs SET status=\'failed\',error_code=\'PROVIDER_FAILURE\',error_message=$1,completed_at=NOW() WHERE id=$2',[last,run.rows[0].id]);throw new Error(last);}
}
export {safeJson};
