import { createHash, createPrivateKey, createPublicKey, randomBytes, randomUUID, scrypt as scryptCallback, sign as signData, timingSafeEqual, verify as verifyData } from 'node:crypto';
import { promisify } from 'node:util';
import type { FastifyRequest, FastifyReply } from 'fastify';
import type { Pool } from 'pg';
const scrypt=promisify(scryptCallback); const PRIVATE_KEY_B64=process.env.IDENTITY_PRIVATE_KEY_B64;
if(!PRIVATE_KEY_B64)throw new Error('IDENTITY_PRIVATE_KEY_B64 must be configured');
const privateKey=createPrivateKey({key:Buffer.from(PRIVATE_KEY_B64,'base64'),format:'der',type:'pkcs8'}); const publicKey=createPublicKey(privateKey); const TOKEN_TTL_SECONDS=3600; const issuer=()=>process.env.IDENTITY_ISSUER??'anpardaz-platform';
type Claims={sub:string;email:string;role:string;iss:string;aud:'anpardaz-ecosystem';iat:number;exp:number}; type AuthBody={email?:string;password?:string};
const b64=(v:string|Buffer)=>Buffer.from(v).toString('base64url');
async function hashPassword(p:string){const s=randomBytes(16).toString('base64url');const d=(await scrypt(p,s,64)) as Buffer;return `scrypt$${s}$${d.toString('base64url')}`;}
async function verifyPassword(p:string,x:string){const parts=x.split('$');if(parts.length!==3||parts[0]!=='scrypt'||!parts[1]||!parts[2])return false;let expected:Buffer;try{expected=Buffer.from(parts[2],'base64url');}catch{return false;}if(expected.length!==64)return false;const actual=(await scrypt(p,parts[1],expected.length)) as Buffer;return timingSafeEqual(expected,actual);}
function createToken(c:Claims){const h=b64(JSON.stringify({alg:'EdDSA',typ:'JWT'})),p=b64(JSON.stringify(c));const s=signData(null,Buffer.from(`${h}.${p}`),privateKey).toString('base64url');return `${h}.${p}.${s}`;}
const valid=(b:AuthBody):b is Required<AuthBody>=>typeof b.email==='string'&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(b.email)&&typeof b.password==='string'&&b.password.length>=10&&b.password.length<=128;
let lastRateLimitCleanup=0;
async function allowAuthAttempt(pool:Pool,req:FastifyRequest,scope:string,identity:string,limit:number){const minute=new Date(Math.floor(Date.now()/60000)*60000);if(minute.getTime()-lastRateLimitCleanup>=600000){lastRateLimitCleanup=minute.getTime();await pool.query("DELETE FROM auth_rate_limits WHERE window_start < NOW() - INTERVAL '24 hours'").catch(()=>{});}const clientKey=createHash('sha256').update(`${scope}|${req.ip}|${identity.toLowerCase()}`).digest('hex');const r=await pool.query<{request_count:number}>(`INSERT INTO auth_rate_limits(scope,client_key,window_start,request_count) VALUES($1,$2,$3,1) ON CONFLICT(scope,client_key,window_start) DO UPDATE SET request_count=auth_rate_limits.request_count+1 RETURNING request_count`,[scope,clientKey,minute]);return r.rows[0].request_count<=limit;}
export async function ensurePlatformUser(pool:Pool,auth:Claims){const existing=await pool.query<{id:string}>('SELECT id FROM platform_users WHERE identity_id=$1 LIMIT 1',[auth.sub]);if(existing.rows[0]){await pool.query('UPDATE platform_users SET email=$1 WHERE id=$2',[auth.email,existing.rows[0].id]);return existing.rows[0].id;}const r=await pool.query<{id:string}>('INSERT INTO platform_users(identity_id,email,display_name,role) VALUES($1,$2,$3,$4) ON CONFLICT(identity_id) DO UPDATE SET email=EXCLUDED.email RETURNING id',[auth.sub,auth.email,auth.email.split('@')[0],auth.role]);return r.rows[0].id;}
export function registerAuthRoutes(app:{post:Function},pool:Pool){
 app.post('/api/v1/auth/register',async(req:FastifyRequest,reply:FastifyReply)=>{const b=(req.body??{}) as AuthBody;if(!valid(b))return reply.code(400).send({error:'invalid_credentials'});const email=b.email.trim().toLowerCase();if(!(await allowAuthAttempt(pool,req,'register',email,5)))return reply.code(429).send({error:'too_many_requests'});try{const r=await pool.query<{identity_id:string;role:string}>(`INSERT INTO platform_users(identity_id,email,password_hash,display_name,role) VALUES($1,$2,$3,$4,$5) RETURNING identity_id,role`,[randomUUID(),email,await hashPassword(b.password),email.split('@')[0],'user']);const u=r.rows[0],now=Math.floor(Date.now()/1000);return reply.code(201).send({accessToken:createToken({sub:u.identity_id,email,role:u.role,iss:issuer(),aud:'anpardaz-ecosystem',iat:now,exp:now+TOKEN_TTL_SECONDS}),expiresIn:TOKEN_TTL_SECONDS});}catch(e:any){if(e?.code==='23505')return reply.code(409).send({error:'email_already_registered'});req.log.error(e);return reply.code(500).send({error:'registration_failed'});}});
 app.post('/api/v1/auth/login',async(req:FastifyRequest,reply:FastifyReply)=>{const b=(req.body??{}) as AuthBody;if(!valid(b))return reply.code(400).send({error:'invalid_credentials'});const email=b.email.trim().toLowerCase();if(!(await allowAuthAttempt(pool,req,'login',email,10)))return reply.code(429).send({error:'too_many_requests'});const r=await pool.query<{identity_id:string;email:string;password_hash:string;role:string;status:string}>(`SELECT identity_id,email,password_hash,role,status FROM platform_users WHERE LOWER(email)=LOWER($1) LIMIT 1`,[email]);const u=r.rows[0];if(!u?.password_hash||u.status!=='active'||!(await verifyPassword(b.password,u.password_hash)))return reply.code(401).send({error:'invalid_credentials'});await pool.query('UPDATE platform_users SET last_login_at=NOW() WHERE identity_id=$1',[u.identity_id]).catch(()=>{});const now=Math.floor(Date.now()/1000);return {accessToken:createToken({sub:u.identity_id,email:u.email,role:u.role,iss:issuer(),aud:'anpardaz-ecosystem',iat:now,exp:now+TOKEN_TTL_SECONDS}),expiresIn:TOKEN_TTL_SECONDS};});
}
export function verifyIdentityToken(t:string):Claims|null{if(typeof t!=='string'||t.length<32||t.length>8192)return null;const parts=t.split('.');if(parts.length!==3)return null;const[h,p,s]=parts;if(!h||!p||!s)return null;try{const header=JSON.parse(Buffer.from(h,'base64url').toString()) as {alg?:string;typ?:string};if(header.alg!=='EdDSA'||header.typ!=='JWT')return null;if(!verifyData(null,Buffer.from(`${h}.${p}`),publicKey,Buffer.from(s,'base64url')))return null;const c=JSON.parse(Buffer.from(p,'base64url').toString()) as Partial<Claims>;const now=Math.floor(Date.now()/1000);if(typeof c.sub!=='string'||!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(c.sub))return null;if(typeof c.email!=='string'||!valid({email:c.email,password:'0123456789'}))return null;if(typeof c.role!=='string'||!['user','admin','super_admin','operator','editor','moderator','support'].includes(c.role))return null;if(c.aud!=='anpardaz-ecosystem'||c.iss!==issuer()||typeof c.iat!=='number'||typeof c.exp!=='number'||!Number.isSafeInteger(c.iat)||!Number.isSafeInteger(c.exp)||c.iat>now+60||c.exp<=now||c.exp>c.iat+TOKEN_TTL_SECONDS)return null;return c as Claims;}catch{return null;}}
export async function requireAuth(req:FastifyRequest,reply:FastifyReply){const h=req.headers.authorization;const c=h?.startsWith('Bearer ')?verifyIdentityToken(h.slice(7)):null;if(!c)return reply.code(401).send({error:'unauthorized'});(req as FastifyRequest&{auth:Claims}).auth=c;}
export type AuthClaims=Claims;
