import type {FastifyInstance,FastifyRequest,FastifyReply} from 'fastify';
import type {Pool} from 'pg';
import {ensureCustomer,requireAuth} from '../auth.js';
type R=FastifyRequest&{auth:{sub:string;email:string;role:string}};const r=(x:FastifyRequest)=>x as R;const money=/^(?:0|[1-9]\d{0,15})(?:\.\d{1,8})?$/;const valid=(v:unknown)=>typeof v==='string'&&money.test(v)&&v!=='0';const sid=(v:unknown)=>typeof v==='number'&&Number.isSafeInteger(v)&&v>0;const idem=(v:unknown)=>typeof v==='string'&&v.length>=8&&v.length<=200;
export function registerBankingRoutes(app:FastifyInstance,pool:Pool){
 app.get('/api/v1/cards',{preHandler:requireAuth},async(req)=>{const c=await ensureCustomer(pool,r(req).auth);return{cards:(await pool.query('SELECT id,account_id,last4,status,created_at FROM cards WHERE customer_id=$1 ORDER BY created_at DESC',[c])).rows};});
 app.post('/api/v1/cards',{preHandler:requireAuth},async(req,reply)=>{const c=await ensureCustomer(pool,r(req).auth),b=(req.body??{}) as any;if(!sid(b.accountId)||typeof b.last4!=='string'||!/^\d{4}$/.test(b.last4)||typeof b.cardToken!=='string'||b.cardToken.length<16)return reply.code(400).send({error:'invalid_card'});const owner=await pool.query('SELECT id FROM accounts WHERE id=$1 AND customer_id=$2',[b.accountId,c]);if(!owner.rows[0])return reply.code(404).send({error:'account_not_found'});try{const x=await pool.query('INSERT INTO cards(customer_id,account_id,card_token,last4) VALUES($1,$2,$3,$4) RETURNING id,account_id,last4,status,created_at',[c,b.accountId,b.cardToken,b.last4]);return reply.code(201).send({card:x.rows[0]});}catch(e:any){if(e?.code==='23505')return reply.code(409).send({error:'card_already_exists'});throw e;}});
 app.get('/api/v1/transfers',{preHandler:requireAuth},async(req)=>{const c=await ensureCustomer(pool,r(req).auth);return{transfers:(await pool.query('SELECT * FROM transfer_requests WHERE customer_id=$1 ORDER BY created_at DESC LIMIT 200',[c])).rows};});
 app.post('/api/v1/transfers',{preHandler:requireAuth},async(req,reply)=>{const c=await ensureCustomer(pool,r(req).auth),b=(req.body??{}) as any;if(!sid(b.sourceAccountId)||!valid(b.amount)||typeof b.currency!=='string'||!/^[A-Z]{3}$/.test(b.currency)||!idem(b.idempotencyKey))return reply.code(400).send({error:'invalid_transfer'});if(!sid(b.destinationAccountId)&&typeof b.destinationExternal!=='string')return reply.code(400).send({error:'destination_required'});const own=await pool.query('SELECT id,currency FROM accounts WHERE id=$1 AND customer_id=$2 AND status=\'active\'',[b.sourceAccountId,c]);if(!own.rows[0]||own.rows[0].currency!==b.currency)return reply.code(400).send({error:'invalid_source_account'});try{const x=await pool.query('INSERT INTO transfer_requests(customer_id,source_account_id,destination_account_id,destination_external,amount,currency,description,idempotency_key) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[c,b.sourceAccountId,b.destinationAccountId??null,b.destinationExternal?.trim()??null,b.amount,b.currency,b.description?.trim()??null,b.idempotencyKey]);return reply.code(201).send({transfer:x.rows[0]});}catch(e:any){if(e?.code==='23505'){const x=await pool.query('SELECT * FROM transfer_requests WHERE customer_id=$1 AND idempotency_key=$2',[c,b.idempotencyKey]);return{transfer:x.rows[0],idempotent:true};}throw e;}});
 app.post('/api/v1/transfers/:id/cancel',{preHandler:requireAuth},async(req,reply)=>{const c=await ensureCustomer(pool,r(req).auth),id=Number((req.params as any).id);const x=await pool.query("UPDATE transfer_requests SET status='cancelled',updated_at=NOW() WHERE id=$1 AND customer_id=$2 AND status='pending' RETURNING *",[id,c]);if(!x.rows[0])return reply.code(404).send({error:'transfer_not_cancellable'});return{transfer:x.rows[0]};});
 app.get('/api/v1/topups',{preHandler:requireAuth},async(req)=>{const c=await ensureCustomer(pool,r(req).auth);return{topups:(await pool.query('SELECT * FROM topup_requests WHERE customer_id=$1 ORDER BY created_at DESC LIMIT 200',[c])).rows};});
 app.post('/api/v1/topups',{preHandler:requireAuth},async(req,reply)=>{const c=await ensureCustomer(pool,r(req).auth),b=(req.body??{}) as any;if(!sid(b.accountId)||!valid(b.amount)||typeof b.currency!=='string'||!/^[A-Z]{3}$/.test(b.currency)||!idem(b.idempotencyKey))return reply.code(400).send({error:'invalid_topup'});const own=await pool.query('SELECT id,currency FROM accounts WHERE id=$1 AND customer_id=$2',[b.accountId,c]);if(!own.rows[0]||own.rows[0].currency!==b.currency)return reply.code(400).send({error:'invalid_account'});try{const x=await pool.query('INSERT INTO topup_requests(customer_id,account_id,amount,currency,provider,idempotency_key) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[c,b.accountId,b.amount,b.currency,b.provider??null,b.idempotencyKey]);return reply.code(201).send({topup:x.rows[0]});}catch(e:any){if(e?.code==='23505'){const x=await pool.query('SELECT * FROM topup_requests WHERE customer_id=$1 AND idempotency_key=$2',[c,b.idempotencyKey]);return{topup:x.rows[0],idempotent:true};}throw e;}});
}
