import type { FastifyInstance, FastifyRequest } from 'fastify';
import type { Pool } from 'pg';
import { ensurePlatformUser, requireAuth } from '../auth.js';
type R=FastifyRequest&{auth:{sub:string;email:string;role:string}};
const staff=(r:R)=>['admin','super_admin','operator','support','moderator','editor'].includes(r.auth.role);
const deny=(reply:any)=>reply.code(403).send({error:'forbidden'});
async function audit(pool:Pool,r:R,action:string,type:string,id:string|null,metadata:unknown={}){await pool.query("INSERT INTO audit_logs(identity_id,actor_type,actor_identity_id,action,resource_type,resource_id,metadata) VALUES($1,'admin',$1,$2,$3,$4,$5)",[r.auth.sub,action,type,id,metadata]);}
export function registerControlPlaneRoutes(app:FastifyInstance,pool:Pool){
 app.post('/api/v1/support/tickets',{preHandler:requireAuth},async(req,reply)=>{const r=req as R;const b=(req.body??{}) as {subject?:string;category?:string;priority?:string;externalReference?:string;context?:unknown};if(!b.subject?.trim())return reply.code(400).send({error:'subject_required'});const uid=await ensurePlatformUser(pool,r.auth);const t=await pool.query('INSERT INTO support_tickets(user_id,subject,category,priority,external_reference,context) VALUES($1,$2,COALESCE($3,\'general\'),COALESCE($4,\'normal\'),$5,$6) RETURNING *',[uid,b.subject.trim(),b.category,b.priority,b.externalReference??null,b.context??{}]);await pool.query("INSERT INTO support_ticket_events(ticket_id,actor_identity_id,event_type,new_value) VALUES($1,$2,'created',$3)",[t.rows[0].id,r.auth.sub,t.rows[0]]);return reply.code(201).send({ticket:t.rows[0]});});
 app.get('/api/v1/admin/tickets',{preHandler:requireAuth},async(req,reply)=>{const r=req as R;if(!staff(r))return deny(reply);const q=req.query as {status?:string;priority?:string;limit?:string};const limit=Math.min(Math.max(Number(q.limit??100)||100,1),200);const rows=await pool.query('SELECT t.*,u.identity_id,u.email FROM support_tickets t JOIN platform_users u ON u.id=t.user_id WHERE ($1::text IS NULL OR t.status=$1) AND ($2::text IS NULL OR t.priority=$2) ORDER BY t.updated_at DESC LIMIT $3',[q.status??null,q.priority??null,limit]);return{tickets:rows.rows};});
 app.get('/api/v1/admin/tickets/:id',{preHandler:requireAuth},async(req,reply)=>{const r=req as R;if(!staff(r))return deny(reply);const id=(req.params as {id:string}).id;const t=await pool.query('SELECT t.*,u.identity_id,u.email FROM support_tickets t JOIN platform_users u ON u.id=t.user_id WHERE t.id=$1',[id]);if(!t.rows[0])return reply.code(404).send({error:'ticket_not_found'});const [m,e]=await Promise.all([pool.query('SELECT * FROM support_messages WHERE ticket_id=$1 ORDER BY created_at',[id]),pool.query('SELECT * FROM support_ticket_events WHERE ticket_id=$1 ORDER BY created_at',[id])]);return{ticket:t.rows[0],messages:m.rows,events:e.rows};});
 app.post('/api/v1/admin/tickets/:id/messages',{preHandler:requireAuth},async(req,reply)=>{const r=req as R;if(!staff(r))return deny(reply);const id=(req.params as {id:string}).id,b=(req.body??{}) as {body?:string;internal?:boolean};if(!b.body?.trim())return reply.code(400).send({error:'body_required'});const uid=await ensurePlatformUser(pool,r.auth);const m=await pool.query("INSERT INTO support_messages(ticket_id,sender_type,sender_user_id,body,internal) VALUES($1,'agent',$2,$3,$4) RETURNING *",[id,uid,b.body.trim(),b.internal===true]);await pool.query("UPDATE support_tickets SET updated_at=NOW() WHERE id=$1",[id]);await audit(pool,r,'support_message','support_ticket',id,{internal:b.internal===true});return reply.code(201).send({message:m.rows[0]});});
 app.patch('/api/v1/admin/tickets/:id',{preHandler:requireAuth},async(req,reply)=>{const r=req as R;if(!staff(r))return deny(reply);const id=(req.params as {id:string}).id,b=(req.body??{}) as {status?:string;priority?:string;assignedIdentityId?:string|null};if(b.status&&!['open','pending','resolved','closed'].includes(b.status))return reply.code(400).send({error:'invalid_status'});if(b.priority&&!['low','normal','high','urgent'].includes(b.priority))return reply.code(400).send({error:'invalid_priority'});let assignedId:null|string=null;if(b.assignedIdentityId){const u=await pool.query('SELECT id FROM platform_users WHERE identity_id=$1',[b.assignedIdentityId]);if(!u.rows[0])return reply.code(400).send({error:'assignee_not_found'});assignedId=u.rows[0].id;}const old=await pool.query('SELECT status,priority,assigned_to FROM support_tickets WHERE id=$1',[id]);if(!old.rows[0])return reply.code(404).send({error:'ticket_not_found'});const t=await pool.query('UPDATE support_tickets SET status=COALESCE($1,status),priority=COALESCE($2,priority),assigned_to=CASE WHEN $3::boolean THEN $4 ELSE assigned_to END,updated_at=NOW() WHERE id=$5 RETURNING *',[b.status??null,b.priority??null,Object.prototype.hasOwnProperty.call(b,'assignedIdentityId'),assignedId,id]);await pool.query("INSERT INTO support_ticket_events(ticket_id,actor_identity_id,event_type,old_value,new_value) VALUES($1,$2,'status_changed',$3,$4)",[id,r.auth.sub,old.rows[0],t.rows[0]]);await audit(pool,r,'support_ticket_update','support_ticket',id,{status:b.status,priority:b.priority});return{ticket:t.rows[0]};});
 app.get('/api/v1/notifications',{preHandler:requireAuth},async(req)=>{const r=req as R;const rows=await pool.query('SELECT * FROM notifications WHERE identity_id=$1 ORDER BY created_at DESC LIMIT 100',[r.auth.sub]);return{notifications:rows.rows};});
 app.post('/api/v1/admin/notifications',{preHandler:requireAuth},async(req,reply)=>{const r=req as R;if(!staff(r))return deny(reply);const b=(req.body??{}) as {identityId?:string;channel?:string;type?:string;title?:string;body?:string;data?:unknown};if(!b.identityId||!b.title||!b.body||!['in_app','push','sms','email'].includes(b.channel??''))return reply.code(400).send({error:'invalid_notification'});const n=await pool.query('INSERT INTO notifications(identity_id,channel,type,title,body,data) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[b.identityId,b.channel,b.type??'admin',b.title,b.body,b.data??{}]);await audit(pool,r,'notification_create','notification',String(n.rows[0].id));return reply.code(201).send({notification:n.rows[0]});});
 app.get('/api/v1/admin/market-data/sources',{preHandler:requireAuth},async(req,reply)=>{const r=req as R;if(!staff(r))return deny(reply);const rows=await pool.query('SELECT s.*,h.status,h.last_success_at,h.last_failure_at,h.consecutive_failures,h.last_error FROM market_data_sources s LEFT JOIN market_data_health h ON h.source_id=s.id ORDER BY s.priority,s.name');return{sources:rows.rows};});
 app.get('/api/v1/admin/ai/providers',{preHandler:requireAuth},async(req,reply)=>{const r=req as R;if(!staff(r))return deny(reply);const rows=await pool.query('SELECT id,name,provider_type,base_url,enabled,priority,model_policy,secret_ref,created_at,updated_at FROM ai_providers ORDER BY priority,name');return{providers:rows.rows};});
}
