import type { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';
import type { Pool } from 'pg';
import { ensurePlatformUser, requireAuth } from '../auth.js';
export function registerForumRoutes(app:FastifyInstance,pool:Pool){
 app.get('/api/v1/forum/threads',async(request)=>{const q=request.query as {page?:string;limit?:string};const page=Math.max(1,Number(q.page)||1),limit=Math.min(50,Math.max(1,Number(q.limit)||20));const r=await pool.query('SELECT t.id,t.title,t.status,t.category_id,t.created_at,t.updated_at,u.display_name FROM forum_threads t JOIN platform_users u ON u.id=t.user_id WHERE t.status<>\'archived\' ORDER BY t.updated_at DESC LIMIT $1 OFFSET $2',[limit,(page-1)*limit]);return {items:r.rows,pagination:{page,limit}};});
 app.get<{Params:{id:string}}>('/api/v1/forum/threads/:id',async(request,reply)=>{const id=Number(request.params.id);if(!Number.isSafeInteger(id))return reply.code(400).send({error:'invalid_thread_id'});const t=await pool.query('SELECT id,title,status,category_id,created_at,updated_at FROM forum_threads WHERE id=$1 AND status<>'archived'',[id]);if(!t.rows[0])return reply.code(404).send({error:'thread_not_found'});const p=await pool.query('SELECT p.id,p.body,p.created_at,u.display_name FROM forum_posts p JOIN platform_users u ON u.id=p.user_id WHERE p.thread_id=$1 AND p.moderation_status='visible' ORDER BY p.created_at ASC',[id]);return {thread:t.rows[0],posts:p.rows};});
 app.post<{Body:{title?:string;categoryId?:number}}>('/api/v1/forum/threads',{preHandler:requireAuth},async(request,reply)=>{const auth=(request as FastifyRequest&{auth:any}).auth,b=request.body??{};if(typeof b.title!=='string'||b.title.trim().length<3||b.title.length>200)return reply.code(400).send({error:'invalid_title'});const userId=await ensurePlatformUser(pool,auth);const r=await pool.query('INSERT INTO forum_threads(user_id,category_id,title) VALUES($1,$2,$3) RETURNING *',[userId,b.categoryId??null,b.title.trim()]);return reply.code(201).send({thread:r.rows[0]});});
 app.post<{Params:{id:string};Body:{body?:string}}>('/api/v1/forum/threads/:id/posts',{preHandler:requireAuth},async(request,reply)=>{const auth=(request as FastifyRequest&{auth:any}).auth,id=Number(request.params.id),body=request.body?.body;if(!Number.isSafeInteger(id)||typeof body!=='string'||body.trim().length<1||body.length>10000)return reply.code(400).send({error:'invalid_post'});const thread=await pool.query('SELECT id FROM forum_threads WHERE id=$1 AND status=\'open\'',[id]);if(!thread.rows[0])return reply.code(404).send({error:'thread_not_found'});const userId=await ensurePlatformUser(pool,auth);const r=await pool.query('INSERT INTO forum_posts(thread_id,user_id,body) VALUES($1,$2,$3) RETURNING *',[id,userId,body.trim()]);await pool.query('UPDATE forum_threads SET updated_at=NOW() WHERE id=$1',[id]);return reply.code(201).send({post:r.rows[0]});});
}
