import { createHash } from 'node:crypto';
import type { FastifyInstance, FastifyRequest } from 'fastify';
import type { Pool } from 'pg';
import { requireAuth } from '../auth.js';
type R=FastifyRequest&{auth:{sub:string;role:string}};
const staff=(r:R)=>['admin','super_admin','operator','moderator'].includes(r.auth.role);
const guestHash=(token:string)=>createHash('sha256').update(`${process.env.GUEST_INTERACTION_SECRET??'CHANGE_ME_GUEST_INTERACTION_SECRET'}:${token}`).digest('hex');
const actor=(req:FastifyRequest)=>{const h=req.headers.authorization;return h?.startsWith('Bearer ')?h.slice(7):null;};
export function registerModerationRoutes(app:FastifyInstance,pool:Pool){
 app.post('/api/v1/community/comments',async(req,reply)=>{const b=(req.body??{}) as {targetType?:string;targetId?:string;body?:string;parentId?:number};const allowed=['news','banner','market_product','forum_thread','forum_post','content'];if(!allowed.includes(b.targetType??'')||!b.targetId||!b.body?.trim())return reply.code(400).send({error:'invalid_comment'});let identityId:string|null=null;const token=actor(req);if(token){const auth=(req as R).auth;identityId=auth?.sub??null;}const guest=req.headers['x-guest-token'];const guestToken=typeof guest==='string'?guest:null;if(!identityId&&!guestToken)return reply.code(401).send({error:'guest_token_required'});const gh=identityId?null:guestHash(guestToken!);const c=await pool.query('INSERT INTO community_comments(identity_id,guest_token_hash,target_type,target_id,parent_id,body) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,target_type,target_id,parent_id,body,status,created_at',[identityId,gh,b.targetType,b.targetId,b.parentId??null,b.body.trim()]);return reply.code(201).send({comment:c.rows[0]});});
 app.get('/api/v1/community/comments',async(req)=>{const q=req.query as {targetType?:string;targetId?:string;limit?:string;cursor?:string};const limit=Math.min(Math.max(Number(q.limit??50)||50,1),100);const rows=await pool.query('SELECT id,identity_id,target_type,target_id,parent_id,body,status,created_at FROM community_comments WHERE target_type=$1 AND target_id=$2 AND status=\'visible\' AND ($3::bigint IS NULL OR id<$3) ORDER BY id DESC LIMIT $4',[q.targetType,q.targetId,q.cursor??null,limit]);return{comments:rows.rows,nextCursor:rows.rows.length===limit?String(rows.rows.at(-1).id):null};});
 app.post('/api/v1/community/likes',async(req,reply)=>{const b=(req.body??{}) as {targetType?:string;targetId?:string};if(!b.targetType||!b.targetId)return reply.code(400).send({error:'invalid_target'});const token=actor(req);const identityId=token?(req as R).auth?.sub??null:null;const guest=req.headers['x-guest-token'];const guestToken=typeof guest==='string'?guest:null;if(!identityId&&!guestToken)return reply.code(401).send({error:'guest_token_required'});const gh=identityId?null:guestHash(guestToken!);const existing=await pool.query<{id:string}>('SELECT id FROM community_likes WHERE status=\'active\' AND ((identity_id=$1 AND $1 IS NOT NULL) OR (guest_token_hash=$2 AND $2 IS NOT NULL)) AND target_type=$3 AND target_id=$4 LIMIT 1',[identityId,gh,b.targetType,b.targetId]);if(existing.rows[0]){await pool.query("UPDATE community_likes SET status='removed' WHERE id=$1",[existing.rows[0].id]);return{liked:false};}const l=await pool.query('INSERT INTO community_likes(identity_id,guest_token_hash,target_type,target_id) VALUES($1,$2,$3,$4) RETURNING id',[identityId,gh,b.targetType,b.targetId]);return reply.code(201).send({liked:true,id:l.rows[0].id});});
 app.get('/api/v1/community/likes',async(req)=>{const q=req.query as {targetType?:string;targetId?:string};const r=await pool.query("SELECT count(*)::int AS count FROM community_likes WHERE status='active' AND target_type=$1 AND target_id=$2",[q.targetType,q.targetId]);return{count:r.rows[0].count};});
 app.get('/api/v1/admin/moderation/comments',{preHandler:requireAuth},async(req,reply)=>{const r=req as R;if(!staff(r))return reply.code(403).send({error:'forbidden'});const q=req.query as {status?:string;targetType?:string;targetId?:string;limit?:string};const limit=Math.min(Math.max(Number(q.limit??100)||100,1),200);const rows=await pool.query('SELECT c.*,u.email FROM community_comments c LEFT JOIN platform_users u ON u.identity_id=c.identity_id WHERE ($1::text IS NULL OR c.status=$1) AND ($2::text IS NULL OR c.target_type=$2) AND ($3::text IS NULL OR c.target_id=$3) ORDER BY c.created_at DESC LIMIT $4',[q.status??null,q.targetType??null,q.targetId??null,limit]);return{comments:rows.rows};});
 app.patch('/api/v1/admin/moderation/comments/:id',{preHandler:requireAuth},async(req,reply)=>{const r=req as R;if(!staff(r))return reply.code(403).send({error:'forbidden'});const id=(req.params as {id:string}).id,b=(req.body??{}) as {status?:string;reason?:string};if(!['visible','hidden','deleted','pending','blocked'].includes(b.status??''))return reply.code(400).send({error:'invalid_status'});const c=await pool.query('UPDATE community_comments SET status=$1,moderation_reason=$2,updated_at=NOW() WHERE id=$3 RETURNING *',[b.status,b.reason??null,id]);if(!c.rows[0])return reply.code(404).send({error:'comment_not_found'});await pool.query('INSERT INTO moderation_actions(moderator_identity_id,target_type,target_id,action,reason) VALUES($1,\'comment\',$2,$3,$4)',[r.auth.sub,id,b.status==='deleted'?'delete':b.status==='hidden'?'hide':b.status==='visible'?'restore':'block',b.reason??null]);await pool.query("INSERT INTO audit_logs(identity_id,actor_type,actor_identity_id,action,resource_type,resource_id,reason) VALUES($1,'admin',$1,'moderate','comment',$2,$3)",[r.auth.sub,id,b.reason??null]);return{comment:c.rows[0]};});
 app.get('/api/v1/admin/moderation/likes',{preHandler:requireAuth},async(req,reply)=>{const r=req as R;if(!staff(r))return reply.code(403).send({error:'forbidden'});const q=req.query as {targetType?:string;targetId?:string;limit?:string};const limit=Math.min(Math.max(Number(q.limit??100)||100,1),200);const rows=await pool.query('SELECT l.*,u.email FROM community_likes l LEFT JOIN platform_users u ON u.identity_id=l.identity_id WHERE ($1::text IS NULL OR l.target_type=$1) AND ($2::text IS NULL OR l.target_id=$2) ORDER BY l.created_at DESC LIMIT $3',[q.targetType??null,q.targetId??null,limit]);return{likes:rows.rows};});
 app.delete('/api/v1/admin/moderation/likes/:id',{preHandler:requireAuth},async(req,reply)=>{const r=req as R;if(!staff(r))return reply.code(403).send({error:'forbidden'});const id=(req.params as {id:string}).id;const l=await pool.query("UPDATE community_likes SET status='removed' WHERE id=$1 RETURNING *",[id]);if(!l.rows[0])return reply.code(404).send({error:'like_not_found'});await pool.query("INSERT INTO moderation_actions(moderator_identity_id,target_type,target_id,action) VALUES($1,'like',$2,'remove_like')",[r.auth.sub,id]);await pool.query("INSERT INTO audit_logs(identity_id,actor_type,actor_identity_id,action,resource_type,resource_id) VALUES($1,'admin',$1,'remove','like',$2)",[r.auth.sub,id]);return{like:l.rows[0]};});
}
