import type {FastifyInstance,FastifyRequest,FastifyReply} from 'fastify';
import type {Pool} from 'pg';
import {createHash} from 'node:crypto';
import {ensureCustomer,requireAuth,type AuthClaims} from '../auth.js';
type R=FastifyRequest&{auth:AuthClaims};const r=(x:FastifyRequest)=>x as R;
const dec=/^(?:0|[1-9]\d{0,27})(?:\.\d{1,18})?$/;const amount=(v:unknown)=>typeof v==='string'&&dec.test(v)&&v!=='0'&&!/^0\.0+$/.test(v);const id=(v:unknown)=>typeof v==='number'&&Number.isSafeInteger(v)&&v>0;const idem=(v:unknown)=>typeof v==='string'&&v.length>=8&&v.length<=200;const fp=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
export function registerTradingRoutes(app:FastifyInstance,pool:Pool){
 app.post('/api/v1/orders',{preHandler:requireAuth},async(req,reply)=>{const a=r(req),b=(req.body??{}) as any;if(!id(b.baseAssetId)||!id(b.quoteAssetId)||b.baseAssetId===b.quoteAssetId||!['buy','sell'].includes(b.side)||!['market','limit'].includes(b.orderType)||!amount(b.quantity)||(b.orderType==='limit'&&!amount(b.price))||(b.orderType==='market'&&b.price!=null)||!idem(b.idempotencyKey))return reply.code(400).send({error:'invalid_order'});const customer=await ensureCustomer(pool,a.auth);const assets=await pool.query("SELECT id FROM assets WHERE id=ANY($1::bigint[]) AND status='active'",[[b.baseAssetId,b.quoteAssetId]]);if(assets.rows.length!==2)return reply.code(400).send({error:'asset_not_available'});const requestFingerprint=fp({baseAssetId:b.baseAssetId,quoteAssetId:b.quoteAssetId,side:b.side,orderType:b.orderType,quantity:b.quantity,price:b.price??null});try{const x=await pool.query('INSERT INTO orders(customer_id,base_asset_id,quote_asset_id,side,order_type,quantity,price,idempotency_key) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[customer,b.baseAssetId,b.quoteAssetId,b.side,b.orderType,b.quantity,b.price??null,b.idempotencyKey]);return reply.code(201).send({order:x.rows[0]});}catch(e:any){if(e?.code==='23505'){const x=await pool.query('SELECT * FROM orders WHERE customer_id=$1 AND idempotency_key=$2',[customer,b.idempotencyKey]);const existing=x.rows[0];const existingFingerprint=fp({baseAssetId:existing?.base_asset_id,quoteAssetId:existing?.quote_asset_id,side:existing?.side,orderType:existing?.order_type,quantity:existing?.quantity,price:existing?.price??null});if(existingFingerprint!==requestFingerprint)return reply.code(409).send({error:'idempotency_key_reused'});return{order:existing,idempotent:true};}throw e;}});
 app.get('/api/v1/orders',{preHandler:requireAuth},async(req)=>{const customer=await ensureCustomer(pool,r(req).auth);return{orders:(await pool.query('SELECT * FROM orders WHERE customer_id=$1 ORDER BY created_at DESC LIMIT 200',[customer])).rows};});
 app.post('/api/v1/orders/:id/cancel',{preHandler:requireAuth},async(req,reply)=>{const customer=await ensureCustomer(pool,r(req).auth),orderId=Number((req.params as any).id);const x=await pool.query("UPDATE orders SET status='cancelled' WHERE id=$1 AND customer_id=$2 AND status IN ('open','partially_filled') RETURNING *",[orderId,customer]);if(!x.rows[0])return reply.code(404).send({error:'cancellable_order_not_found'});return{order:x.rows[0]};});
 app.get('/api/v1/orders/:id/trades',{preHandler:requireAuth},async(req)=>{const customer=await ensureCustomer(pool,r(req).auth),orderId=Number((req.params as any).id);return{trades:(await pool.query('SELECT t.* FROM trades t JOIN orders o ON o.id=t.order_id WHERE t.order_id=$1 AND o.customer_id=$2 ORDER BY t.created_at DESC',[orderId,customer])).rows};});
 app.get('/api/v1/trades',{preHandler:requireAuth},async(req)=>{const customer=await ensureCustomer(pool,r(req).auth);return{trades:(await pool.query('SELECT t.*,o.base_asset_id,o.quote_asset_id,o.side FROM trades t JOIN orders o ON o.id=t.order_id WHERE o.customer_id=$1 ORDER BY t.created_at DESC LIMIT 200',[customer])).rows};});
 app.get('/api/v1/deposits',{preHandler:requireAuth},async(req)=>{const customer=await ensureCustomer(pool,r(req).auth);return{deposits:(await pool.query('SELECT d.*,a.symbol,a.name FROM deposits d JOIN assets a ON a.id=d.asset_id WHERE d.customer_id=$1 ORDER BY d.created_at DESC LIMIT 200',[customer])).rows};});
 app.post('/api/v1/deposits',{preHandler:requireAuth},async(req,reply)=>{const customer=await ensureCustomer(pool,r(req).auth),b=(req.body??{}) as any;if(!id(b.assetId)||!amount(b.amount)||typeof b.network!=='string'||!b.network.trim()||b.network.length>50||!idem(b.idempotencyKey))return reply.code(400).send({error:'invalid_deposit'});const requestFingerprint=fp({assetId:b.assetId,amount:b.amount,network:b.network.trim(),externalReference:b.externalReference??null});try{const x=await pool.query('INSERT INTO deposits(customer_id,asset_id,amount,network,external_reference,idempotency_key) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[customer,b.assetId,b.amount,b.network.trim(),b.externalReference??null,b.idempotencyKey]);return reply.code(201).send({deposit:x.rows[0]});}catch(e:any){if(e?.code==='23505'){const x=await pool.query('SELECT * FROM deposits WHERE customer_id=$1 AND idempotency_key=$2',[customer,b.idempotencyKey]);const existing=x.rows[0];const existingFingerprint=fp({assetId:existing?.asset_id,amount:existing?.amount,network:existing?.network,externalReference:existing?.external_reference??null});if(existingFingerprint!==requestFingerprint)return reply.code(409).send({error:'idempotency_key_reused'});return{deposit:existing,idempotent:true};}throw e;}});
 app.get('/api/v1/withdrawals',{preHandler:requireAuth},async(req)=>{const customer=await ensureCustomer(pool,r(req).auth);return{withdrawals:(await pool.query('SELECT w.*,a.symbol,a.name FROM withdrawals w JOIN assets a ON a.id=w.asset_id WHERE w.customer_id=$1 ORDER BY w.created_at DESC LIMIT 200',[customer])).rows};});
 app.post('/api/v1/withdrawals',{preHandler:requireAuth},async(req,reply)=>{const customer=await ensureCustomer(pool,r(req).auth),b=(req.body??{}) as any;if(!id(b.assetId)||!amount(b.amount)||typeof b.network!=='string'||!b.network.trim()||typeof b.destination!=='string'||b.destination.length<10||b.destination.length>500||!idem(b.idempotencyKey))return reply.code(400).send({error:'invalid_withdrawal'});const requestFingerprint=fp({assetId:b.assetId,amount:b.amount,network:b.network.trim(),destination:b.destination.trim()});try{const x=await pool.query('INSERT INTO withdrawals(customer_id,asset_id,amount,network,destination,idempotency_key) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[customer,b.assetId,b.amount,b.network.trim(),b.destination.trim(),b.idempotencyKey]);return reply.code(201).send({withdrawal:x.rows[0]});}catch(e:any){if(e?.code==='23505'){const x=await pool.query('SELECT * FROM withdrawals WHERE customer_id=$1 AND idempotency_key=$2',[customer,b.idempotencyKey]);const existing=x.rows[0];const existingFingerprint=fp({assetId:existing?.asset_id,amount:existing?.amount,network:existing?.network,destination:existing?.destination});if(existingFingerprint!==requestFingerprint)return reply.code(409).send({error:'idempotency_key_reused'});return{withdrawal:existing,idempotent:true};}throw e;}});
 app.post('/api/v1/withdrawals/:id/cancel',{preHandler:requireAuth},async(req,reply)=>{const customer=await ensureCustomer(pool,r(req).auth),wid=Number((req.params as any).id);const x=await pool.query("UPDATE withdrawals SET status='cancelled' WHERE id=$1 AND customer_id=$2 AND status='pending' RETURNING *",[wid,customer]);if(!x.rows[0])return reply.code(404).send({error:'cancellable_withdrawal_not_found'});return{withdrawal:x.rows[0]};});
}
