import type {FastifyInstance,FastifyRequest,FastifyReply} from 'fastify';
import type {Pool} from 'pg';
import {ensureCustomer,requireAuth} from '../auth.js';
type R=FastifyRequest&{auth:{sub:string;email:string;role:string}};
const r=(x:FastifyRequest)=>x as R;
const dec=/^(?:0|[1-9]\d{0,27})(?:\.\d{1,18})?$/;
const amount=(v:unknown)=>typeof v==='string'&&dec.test(v)&&v!=='0'&&!/^0\.0+$/.test(v);
const id=(v:unknown)=>typeof v==='number'&&Number.isSafeInteger(v)&&v>0;
export function registerTradingRoutes(app:FastifyInstance,pool:Pool){
 app.post('/api/v1/orders',{preHandler:requireAuth},async(req,reply)=>{const a=r(req),b=(req.body??{}) as any;if(!id(b.baseAssetId)||!id(b.quoteAssetId)||b.baseAssetId===b.quoteAssetId||!['buy','sell'].includes(b.side)||!['market','limit'].includes(b.orderType)||!amount(b.quantity)||(b.orderType==='limit'&&!amount(b.price)))return reply.code(400).send({error:'invalid_order'});const customer=await ensureCustomer(pool,a.auth);const assets=await pool.query("SELECT id FROM assets WHERE id=ANY($1::bigint[]) AND status='active'",[[b.baseAssetId,b.quoteAssetId]]);if(assets.rows.length!==2)return reply.code(400).send({error:'asset_not_available'});const key=typeof b.idempotencyKey==='string'&&b.idempotencyKey.length<=200?b.idempotencyKey:null;if(!key)return reply.code(400).send({error:'idempotency_key_required'});try{const x=await pool.query('INSERT INTO orders(customer_id,base_asset_id,quote_asset_id,side,order_type,quantity,price) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[customer,b.baseAssetId,b.quoteAssetId,b.side,b.orderType,b.quantity,b.price??null]);return reply.code(201).send({order:x.rows[0]});}catch(e:any){if(e?.code==='23505')return reply.code(409).send({error:'order_conflict'});throw e;}});
 app.post('/api/v1/orders/:id/cancel',{preHandler:requireAuth},async(req,reply)=>{const a=r(req),orderId=Number((req.params as any).id);const customer=await ensureCustomer(pool,a.auth);const x=await pool.query("UPDATE orders SET status='cancelled' WHERE id=$1 AND customer_id=$2 AND status IN ('open','partially_filled') RETURNING *",[orderId,customer]);if(!x.rows[0])return reply.code(404).send({error:'cancellable_order_not_found'});return{order:x.rows[0]};});
 app.get('/api/v1/orders/:id/trades',{preHandler:requireAuth},async(req,reply)=>{const customer=await ensureCustomer(pool,r(req).auth),orderId=Number((req.params as any).id);const x=await pool.query('SELECT t.* FROM trades t JOIN orders o ON o.id=t.order_id WHERE t.order_id=$1 AND o.customer_id=$2 ORDER BY t.created_at DESC',[orderId,customer]);return{trades:x.rows};});
 app.get('/api/v1/trades',{preHandler:requireAuth},async(req)=>{const customer=await ensureCustomer(pool,r(req).auth);const x=await pool.query('SELECT t.*,o.base_asset_id,o.quote_asset_id,o.side FROM trades t JOIN orders o ON o.id=t.order_id WHERE o.customer_id=$1 ORDER BY t.created_at DESC LIMIT 200',[customer]);return{trades:x.rows};});
 app.get('/api/v1/deposits',{preHandler:requireAuth},async(req)=>{const customer=await ensureCustomer(pool,r(req).auth);return{deposits:(await pool.query('SELECT d.*,a.symbol,a.name FROM deposits d JOIN assets a ON a.id=d.asset_id WHERE d.customer_id=$1 ORDER BY d.created_at DESC LIMIT 200',[customer])).rows};});
 app.post('/api/v1/deposits',{preHandler:requireAuth},async(req,reply)=>{const customer=await ensureCustomer(pool,r(req).auth),b=(req.body??{}) as any;if(!id(b.assetId)||!amount(b.amount)||typeof b.network!=='string'||b.network.length>50)return reply.code(400).send({error:'invalid_deposit'});const x=await pool.query("INSERT INTO deposits(customer_id,asset_id,amount,network,external_reference) VALUES($1,$2,$3,$4,$5) RETURNING *",[customer,b.assetId,b.amount,b.network.trim(),b.externalReference??null]);return reply.code(201).send({deposit:x.rows[0]});});
 app.get('/api/v1/withdrawals',{preHandler:requireAuth},async(req)=>{const customer=await ensureCustomer(pool,r(req).auth);return{withdrawals:(await pool.query('SELECT w.*,a.symbol,a.name FROM withdrawals w JOIN assets a ON a.id=w.asset_id WHERE w.customer_id=$1 ORDER BY w.created_at DESC LIMIT 200',[customer])).rows};});
 app.post('/api/v1/withdrawals',{preHandler:requireAuth},async(req,reply)=>{const customer=await ensureCustomer(pool,r(req).auth),b=(req.body??{}) as any;if(!id(b.assetId)||!amount(b.amount)||typeof b.network!=='string'||!b.network.trim()||typeof b.destination!=='string'||b.destination.length<10||b.destination.length>500)return reply.code(400).send({error:'invalid_withdrawal'});const x=await pool.query("INSERT INTO withdrawals(customer_id,asset_id,amount,network,destination) VALUES($1,$2,$3,$4,$5) RETURNING *",[customer,b.assetId,b.amount,b.network.trim(),b.destination.trim()]);return reply.code(201).send({withdrawal:x.rows[0],status:'pending'});});
 app.post('/api/v1/withdrawals/:id/cancel',{preHandler:requireAuth},async(req,reply)=>{const customer=await ensureCustomer(pool,r(req).auth),wid=Number((req.params as any).id);const x=await pool.query("UPDATE withdrawals SET status='cancelled' WHERE id=$1 AND customer_id=$2 AND status='pending' RETURNING *",[wid,customer]);if(!x.rows[0])return reply.code(404).send({error:'cancellable_withdrawal_not_found'});return{withdrawal:x.rows[0]};});
}
